#!/usr/bin/env bash

# Setting variables
red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`
bld=`tput bold`
fmt="%-12s%-12s\n"
curdate=`date +%Y%m%d`

function show_usage()
{
    echo -e "\nUsage: install.sh youtube_link file_path/file_name to save.\nScript for downloading youtube tracks\n"
    echo ""
    exit 1
}
function program_is_installed()
{
    echo "Checking installed tools..."
    local count=0
    echo ""
    for i in "$@"
    do
        type $i >/dev/null 2>&1 && printf " $fmt" "$i" "${bld}${green}+${reset}"\
        || { printf " $fmt" "$i" "${bld}${red}-${reset}"; count=$((count+1)); }
    done
    if [ ! $count == 0 ]
    then
        echo -e "\nSome tools are missing, install them!\n"
    fi
}

[ ! "$#" == 2 ] && show_usage
program_is_installed youtube-dl

if [ ! $? == 0 ]
then
    show_usage
fi

youtube-dl -x -o "${2}.%(ext)s" ${1}
exit 0

