#!/bin/bash

video=(/filo/Video/Movies
       /filo/Video/TVShows)

for i in ${video[@]}
do
	videonames+=("`find $i -type f | grep -vi x-art | egrep -v "(\.srt|\.aac|\.ogg)"`")
done

sel="$(printf '%s\n' "${videonames[@]}" | sort -f | dmenu -l 30 -p "Select file: ")"

if [ "$sel" ]
then
    mpv "$sel"
else
    exit 1
fi

