#!/bin/bash

case $1 in
"")
    length=16
    tr -dc A-Za-z0-9_ < /dev/urandom | head -c ${length} | xargs
    ;;
*[0-9]*)
    length=$1
    tr -dc A-Za-z0-9_ < /dev/urandom | head -c ${length} | xargs
    ;;
*)
    echo "ERROR: Use a number!"
    exit 1
    ;;
esac
