#!/bin/bash

slavedb=eshp-eom-db-2
datapath="/var/lib/pgsql/10/data"

if [ $# != 1 ]
then
        echo -e "
Script for Backing up Postgres Data dir.
Usage: $0 (start|-s)
"
        exit 1
fi

case $1 in
    start|-s)
        echo "Startig PG Base Backup"
        psql -U postgres -h 127.0.0.1 -c "SELECT pg_start_backup('label', true)" > sql.log
        sleep 2
        rsync -a $datapath/* $slavedb:$datapath/ --exclude postmaster.pid --progress 2>&1 | tee rsync.log
        sleep 2
        psql -U postgres -h 127.0.0.1 -c "SELECT pg_stop_backup()" >> sql.log
        ;;
    *)
        echo "Exiting..."
        exit 0
        ;;
esac

