#!/bin/bash

slavedb=$1
datapath=$2

if [ $# != 3 ]
then
        echo -e "
Script for Backing up Postgres Data dir.
Usage: $0 slave-db-host datadir (start|-s)
"
        exit 1
fi

case $3 in
    start|-s)
        echo "Startig PG Base Backup"
        psql -U postgres -h 127.0.0.1 -c "SELECT pg_start_backup('label', true)" > sql.log
        sleep 2
        rsync -a $datapath/* $slavedb:$datapath/ --exclude postmaster.pid --progress 2>&1 | tee rsync.log
        sleep 2
        psql -U postgres -h 127.0.0.1 -c "SELECT pg_stop_backup()" >> sql.log
        ;;
    *)
        echo "Exiting..."
        exit 0
        ;;
esac

